---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: capi-provider-azure
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./mgmt-cluster/addons/capi/providers/azure
  prune: true
  wait: true
  dependsOn:
    - name: capi-provider-core
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: capz-creds
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: capi-provider-azure
  path: ./mgmt-cluster/bases/capi/azure
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config