apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flamingo
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./mgmt-cluster/addons/flamingo
  prune: true
  wait: true
  dependsOn:
    - name: wge
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config