apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: capi-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./mgmt-cluster/addons/capi/operator
  prune: true
  wait: true
  dependsOn:
    - name: wge
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: capi-provider-core
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./mgmt-cluster/addons/capi/providers/core
  prune: true
  wait: true
  dependsOn:
    - name: capi-operator
  sourceRef:
    kind: GitRepository
    name: global-config
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config

