apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: wge-leaf-config
  namespace: wge
spec:
  dependsOn:
    - name: wge-sa
      namespace: flux-system
  interval: 10m0s
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: global-config
    namespace: flux-system
  path: ./leaf-clusters/wge-leaf-config
  prune: true
  timeout: 5m
  wait: true
  postBuild:
    substitute:
      clusterName: kind-localhost-ww-paulc-dell
      GitHubOrg: ww-gitops
      GitHubRepo: paulc-dell
      globalGitHubOrg: ww-gitops
      globalGitHubRepo: global-config
      globalGitHubBranch: main
      awsAccountId: "\"749339757188\""
      prefixName: ww-pc-dell
      awsRegion: eu-west-1
      awsTagCreator: paul.carlton@weave.works
      awsTagCustomer: weaveworks-cx
      awsTagProjectGid: "\"99999\""
      userEmail: paul.carlton@weave.works
      commitUser: paulcarlton-ww
      resourceName: kind
      templateNamespace: wge
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wge-leaf
  namespace: wge
spec:
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: global-config
    namespace: flux-system
  timeout: 5m
  wait: true
  dependsOn:
  - name: wge-leaf-config
  interval: 5m0s
  path: ./leaf-clusters/wge-leaf
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wge-leaf-apps
  namespace: wge
spec:
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: global-config
    namespace: flux-system
  timeout: 5m
  wait: true
  dependsOn:
  - name: wge-leaf
  interval: 5m0s
  path: ./leaf-clusters/wge-leaf-apps
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-config